# -*- coding: utf-8 -*-
"""03_collections_exercise_campionati_ns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VcPvuFdv_FbijJGDVH1GHIww7R6Be3Fa

## 1. Campionati studenteschi

Creiamo una struttura dati in grado di contenere i risultati di campionati studenteschi di atletica.
La struttura sarà composta da un dizionario avente come chiave: "cognome nome" dell'atleta; e come valore: una lista di tuple.

Per ogni atleta la lista contiene inzialmente 3 tuple, una per ogni disciplina di gara. Ogni tupla ha: in prima posizione il nome della disciplina, in seconda una tupla con il tempo riportato (min,sec,cent), in terza la categoria.  



<table>
    <tr><td>Nominativo atleta</td><td>corsa campestre</td><td>corsa 100mt.</td><td>corsa 200mt</td></tr>
    <tr><td>Giuseppe Gullo</td><td>TEMPO: (1,21,0), CATEGORIA: Juniores mas</td><td>TEMPO: (0,13,0), CATEGORIA:Juniores mas </td><td>TEMPO:(0,29,19) , CATEGORIA:Juniores mas</td></tr>
    <tr><td>Antonia Barbera</td><td>TEMPO: (1,39,11),CATEGORIA: Juniores fem</td><td>TEMPO: (0,18,0), CATEGORIA:Juniores fem </td><td>TEMPO:(0,30,20) , CATEGORIA:Juniores fem</td></tr>
    <tr><td>Nicola Esposito</td><td>TEMPO: (1,43,22),CATEGORIA: Juniores mas</td><td>TEMPO:(0, 14,0), CATEGORIA:Juniores mas </td><td>TEMPO:(0,36,19) , CATEGORIA:Juniores mas</td></tr></table>

1. Popola il dizionario con i dati qui sopra.
2. Aggiungi alla struttura il tuo nominativo con valori a scelta, tranne il numero di secondi che deve essere ([N il tuo numero di registro](https://www.umanet.net/profiles/profile/list/28)).
3. Aggiungi la 4.disciplina sportiva 'corsa ad ostacoli 400 mt' per ogni atleta con la relativa categoria e tempi a tua scelta<br>
4. Stampa la tupla con le informazioni sulla disciplina sportiva corsa campestre per  l'atleta Giuseppe Gullo
5. Stampa i singoli valori della tupla con le informazioni sulla disciplina corsa 200 mt. per Nicola Esposito
6. Stampa il tempo di Antonia Barbera nella corsa 100 mt separando min,sec,cent.
7. Stampa il tempo massimo riportato nella corsa 200mt della categoria Juniores mas (guarda l'aiuto)
8. Stampa il tempo minimo riportato nella corsa 100mt. della categoria Juniores mas. e lo studente che lo ha realizzato (peso 2)
9. Stampa la media dei tempi nella corsa campestre della categoria Juniores mas (peso 2) (guarda l'aiuto)
10. Realizzare le opportune funzioni per aggiungere al dizionario i dati validi relativi alle 4 gare per un nuovo atleta (peso 2)
"""

# Aiuto per il punto 7
tempi = [(2, 15, 50), (2, 27, 45), (3, 10, 30)]
max_tempo = max(tempi)
print(max_tempo)

# Aiuto per il punto 9
def tempo_medio(tempi):
    # Inizializza le variabili per sommare i tempi
    totale_minuti = 0
    totale_secondi = 0
    totale_centesimi = 0

    # Somma i tempi
    #  ...

    # Calcola il numero totale di tempi
    #totale_tempi = ....


    media_minuti = totale_minuti / totale_tempi
    media_secondi = totale_secondi / totale_tempi
    media_centesimi = totale_centesimi / totale_tempi


    return [int(media_minuti), int(media_secondi), int(media_centesimi)]


tempi_di_gara = [(2, 45, 50), (2, 32, 65), (2, 48, 80)]

media = tempo_medio(tempi_di_gara)

print(f"Tempo medio di gara: {media[0]:2d}:{media[1]:2d}.{media[2]:02d}")

#1. Popola il dizionario con i dati qui sopra.
dizionario = {
    "Giuseppe Gullo": [
        ("corsa campestre", (1, 21, 0), "Juniores mas"),
        ("corsa 100mt", (0, 13, 0), "Juniores mas"),
        ("corsa 200mt", (0, 29, 19), "Juniores mas")
    ],
    "Antonia Barbera": [
        ("corsa campestre", (1, 39, 11), "Juniores fem"),
        ("corsa 100mt", (0, 18, 0), "Juniores fem"),
        ("corsa 200mt", (0, 30, 20), "Juniores fem")
    ],
    "Nicola Esposito": [
        ("corsa campestre", (1, 43, 22), "Juniores mas"),
        ("corsa 100mt", (0, 14, 0), "Juniores mas"),
        ("corsa 200mt", (0, 36, 19), "Juniores mas")
    ]
}

#2. Aggiungi alla struttura il tuo nominativo con valori a scelta, tranne il numero di secondi che deve essere (N il tuo numero di registro).
dizionario["Davide Beolchi"] = [
        ("corsa campestre", (4, 3, 0), "Juniores mas"),
        ("corsa 100mt", (1, 3, 0), "Juniores mas"),
        ("corsa 200mt", (2, 3, 0), "Juniores mas")
]

#3. Aggiungi la 4.disciplina sportiva 'corsa ad ostacoli 400 mt' per ogni atleta con la relativa categoria e tempi a tua scelta
for atleta in dizionario:
  dizionario[atleta].append(("corsa ad ostacoli 400mt", (5, 20, 7), "Juniores mas"))

#4. Stampa la tupla con le informazioni sulla disciplina sportiva corsa campestre per l'atleta Giuseppe Gullo
print("Informazioni sulla disciplina sportiva corsa campestre per l'atleta Giuseppe Gullo: ", dizionario["Giuseppe Gullo"][0])

#5. Stampa i singoli valori della tupla con le informazioni sulla disciplina corsa 200 mt. per Nicola Esposito
print("Informazioni sulla disciplina corsa 200 mt. per Nicola Esposito: ", dizionario["Nicola Esposito"][2])

#6. Stampa il tempo di Antonia Barbera nella corsa 100 mt separando min,sec,cent.
minuti, sec, cent = dizionario["Antonia Barbera"][1][1] # separo dati
print(f"Informazioni tempo di Antonia Barbera nella corsa 100 mt separando min: {minuti}, sec: {sec}, cent: {cent}")

#7. Stampa il tempo massimo riportato nella corsa 200mt della categoria Juniores mas (guarda l'aiuto)
listaTempi = []
for atleti in dizionario: # riempio lista
  nomeDisciplina, tempo, categoria = dizionario[atleti][2] # separo dati nella corsa 200mt
  if(categoria ==  "Juniores mas"):
    listaTempi.append(tempo)
max_tempo =  max(listaTempi)
print(f"Tempo massimo riportato nella corsa 200mt della categoria Juniores mas: {max_tempo}")

#8. Stampa il tempo minimo riportato nella corsa 100mt. della categoria Juniores mas. e lo studente che lo ha realizzato (peso 2)
listaTempi = []
listaAtletiMin = [] # utilizzo una lista, questo per comprendere il caso in cui ci siano più persone con gli stessi valori
for atleti in dizionario: # riempio lista
  nomeDisciplina, tempo, categoria = dizionario[atleti][1] # separo dati nella corsa 100mt
  if(categoria ==  "Juniores mas"):
    listaTempi.append(tempo)
min_tempo =  min(listaTempi)


for atleti in dizionario: # ciclo per individuare atleti min
  nomeDisciplina, tempo, categoria = dizionario[atleti][1] # separo dati nella corsa 100mt
  if(tempo == min_tempo):
    listaAtletiMin.append(atleti)

print(f"Tempo minimo riportato nella corsa 100mt. della categoria Juniores mas.: {min_tempo}, e lo/gli studente/i che lo ha realizzato: {listaAtletiMin}")

#9. Stampa la media dei tempi nella corsa campestre della categoria Juniores mas (peso 2) (guarda l'aiuto)
def tempo_medio(listaTempiCampestre):
    totale_minuti = 0
    totale_secondi = 0
    totale_centesimi = 0
    totale_tempi = len(listaTempi)

    for minuti, sec, cent in listaTempiCampestre:
        totale_minuti += minuti
        totale_secondi += sec
        totale_centesimi += cent

    # Calcolo media
    media_minuti = totale_minuti / totale_tempi
    media_secondi = totale_secondi / totale_tempi
    media_centesimi = totale_centesimi / totale_tempi

    return [int(media_minuti), int(media_secondi), int(media_centesimi)]

listaTempiCampestre = []
for atleti in dizionario: # riempio lista
  nomeDisciplina, tempo, categoria = dizionario[atleti][0] # separo dati nella campestre
  if(nomeDisciplina ==  "corsa campestre"):
    if(categoria ==  "Juniores mas"):
      listaTempiCampestre.append(tempo)

media = tempo_medio(listaTempiCampestre)

print(f"Tempo medio di gara corsa campestre: {media[0]:2d}:{media[1]:2d}.{media[2]:02d}")

#10. Realizzare le opportune funzioni per aggiungere al dizionario i dati validi relativi alle 4 gare per un nuovo atleta (peso 2)
def aggiungi_atleta(dizionario):
    i = 0
    lista = []
    nome = aggiungi_nome(dizionario)

    while i < 3:  # ciclo 3 volte per inserire le tre casistiche
        disciplina = aggiungi_nomeDisciplina()
        tempo = aggiungi_tempo()
        categoria = aggiungi_categoria()
        lista.append((disciplina, tempo, categoria))
        i += 1

    dizionario[nome] = lista  # assegno direttamente la lista al dizionario

def aggiungi_nome(dizionario):
    nome = input("Inserisci il nome dell'atleta: ")
    while nome in dizionario:
      nome = input("Nome già presente, reinserisci il nome dell'atleta: ")
    return nome

def aggiungi_nomeDisciplina():
    disciplina = input("Inserisci la disciplina dell'atleta: ")
    return disciplina

def aggiungi_tempo():
    minuti = int(input("Inserisci i minuti: "))
    secondi = int(input("Inserisci i secondi: "))
    centesimi = int(input("Inserisci i centesimi: "))
    return (minuti, secondi, centesimi)

def aggiungi_categoria():
    categoria = input("Inserisci la categoria dell'atleta: ")
    return categoria

aggiungi_atleta(dizionario)
print(dizionario)